### ISSUE TITLE
не советую пользоваться. 

### ISSUE THREAD

**Issue by shveli96** [dle-modules/DLE-AjaxFullStory#12]
около 30 раз пробовал и не работает не каком комбинации в дле 14.2

**Comment by pafnuty** [comment]
@shveli96 Если у вас есть проблема с установкой или использованием модуля, опишите её.
Так же рекомендую провести установку и настройку по инструкции и на шаблоне Default, чтобы избежать возможных ошибок в вашем шаблоне.

**Comment by shveli96** [comment]
В нужном месте любого шаблона вставить минимальный код:
<span data-afs-id="{news-id}">Быстрый просмотр</span>

объясняете это что значит "В нужном месте"

**Comment by pafnuty** [comment]
@shveli96 в том месте, в коде вашего шаблона, в котором предполагается вывод кнопки или ссылки (зависит от дизайна) для открытия модального окна

**Comment by shveli96** [comment]
и текст Быстрый просмотр сам становится кликабельным ? 

на маёом сайте это ни заработал я написал его в шортсторы но осталась текстам  прастим надписом

**Comment by tcse** [comment]
Вот пример работающей версии этого модуля https://moscow-news.online 

скриншот кнопки вызова https://yadi.sk/i/JLUvkyuiIsjxpQ 
скриншот модального окна с содержимым краткой новости https://yadi.sk/i/Fh3Q9eokfQp7yA

**Comment by mondolfini** [comment]
Можно ли использовать в панели администратора ?

**Comment by pafnuty** [comment]
@mondolfini технически да.

**Comment by mondolfini** [comment]
пробовал делать все только в админке, но не работает
