### ISSUE TITLE
Вызов окна по кнопке и по ссылке

### ISSUE THREAD

**Issue by JonyFrost** [dle-modules/DLE-AjaxFullStory#3]
Здравствуйте! Спасибо большое за скрипт, очень пригодился! Подскажите пожалуйста, возможно ли сделать чтобы помимо загрузки окна ajax, еще и прописывался адрес url окна в адресной строке? чтобы можно было вызывать окно и по ссылке к примеру site.ru/linkid(новости), и по кнопке как сейчас. Заранее спасибо!

**Comment by JonyFrost** [comment]
Подскажите пожалуйста, как реализовать то что я спрашивал, заранее спасибо!

**Comment by nurbekov** [comment]
Да,вопрос действительно актуальный и поддерживаю автора. В целом это сделало бы модуль более полноценным. Конечно если не учитывать, что как и просили другие, можно добавить и комментарии...
