### ISSUE TITLE
Обновить модуль до актуальной версии DLE 11

### ISSUE THREAD

**Issue by nurbekov** [dle-modules/DLE-AjaxFullStory#4]
Предлагаю обновить модуль до последней версии DLE 11-ой линейки.
Как нам известно, в новой версии:
- Добавлен новый тип дополнительных полей для публикаций: "Загружаемое изображение".
- Добавлен новый тип дополнительных полей для публикаций: "Загружаемый файл".
- Добавлен новый тип дополнительных полей для публикаций: "Переключатель 'Да' или 'Нет'".
- Для дополнительных полей новостей, имеющих тип поля "Список", добавлена возможность создавать отдельные значения, которые отображаются в списке при добавлении публикации, и те, которые отображаются на сайте после выбора пользователем в качестве значений. (А значит работа самого дополнительного поля изменена)

Попытки решения что принял я: просто скопипастил коды доп тегов с краткой новости - не вышло. Думаю ничего удивительного :)

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-AjaxFullStory/releases/tag/2.0.0
