### ISSUE TITLE
Добавить возможность комментирования и просмотра комментариев.

### ISSUE THREAD

**Issue by nurbekov** [dle-modules/DLE-AjaxFullStory#5]
В целом вопрос с просмотром комментария я решил модулем от Gameer`a. Теперь у меня выводит комментарий, но его к сожалению нельзя оценить. Только обзор. Еще комментарий (а это самое важное) нельзя добавить.
Вы в комментариях к новости писали, что это ни к чему, и модуль предназначен только для предпросмотра новости. Но тут возникает, возможно на первый взгляд не актуальная, но важная при глубоком анализе проблема. 
Например, если это не сайт глобальных новостей, а заметки. То есть пользователь не будет читать целую статью 5 минут, а заметку  в несколько предложений. Открыть новость через модальное окно, тут же оставить комментарий, закрыть окно и смотреть заметки дальше. Ведь это так удобно. Что практикуют крупнейшие социальные сети как facebook и vk (Может и другие, дальше не сижу)

Вы можете убедиться на примере моего сайта - http://kazguu.space/
Чтобы открыть предпрсмотр надо кликнуть на текст, заголовок отправит сразу на полную новость (Это взял от вк)
То есть пользователь за раз просматривает много небольших заметок, и ему не надо будет открывать все в новой вкладке или же постоянно возвращаться на главную. И думаю, что такой сайт не только у меня. Раз люди просят, можно и сделать :) Возможно даже в виде дополнительного функционала, что установится по желанию. Но мы, пользователи что просили об этом, будем однозначно благодарны. :)

---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Слишком узкий кейс, функционал нужен 2% пользователей, установивших модуль, поэтом не думаю, что это стоит усилий.
