### ISSUE TITLE
Не видит новоость соц.сети когда публикуешь!

### ISSUE THREAD

**Issue by Progressive-VIP** [dle-modules/DLE-AjaxFullStory#7]
Добавил в AJAX FULL-STORY окно, Ya.Share  и когда новость публкуешь через соц.сеть то социальные сети не видят эту новость!

можно как либо решить это? 
---
@pafnuty не забудь посмотреть этот тиккет :ticket:

**Comment by pafnuty** [comment]
Обычно всякие сервисы шеринга новостей публикуют ссылку на новость. И также
имеют механизмы, позволяющие добавлять эту ссылку принудительно, если
шеринг происходит не со страницы полной новости.
Вам нужно:
1) настроит корректно публикацию ссылки (возможно доработать модуль).
2) настроить метатеги новости, если это не сделано.

сб, 18 авг. 2018 г., 10:49 Progressive-VIP <notifications@github.com>:
