### ISSUE TITLE
выводит просто текст: Быстрый просмотр

### ISSUE THREAD

**Issue by mondolfo** [dle-modules/DLE-AjaxFullStory#8]
Здравствуйте, простите за глупый вопрос, но я не совсем понял как все это работает!
Вставил:

<span data-afs-id="{news-id}">Быстрый просмотр</span>

в маин, shorstory, fullstory но выводит просто текст: Быстрый просмотр
Цитата

**Comment by pafnuty** [comment]
@mondolfo Добавьте стилей.
например
```html
<span class="btn" data-afs-id="{news-id}">Быстрый просмотр</span>
```
